// Copyright 2026 N1k0droid
// SPDX-License-Identifier: AGPL-3.0-only

// Command notices writes THIRD_PARTY_NOTICES.md from the license and NOTICE files of the modules
// compiled into the server. Run from the repository root: go run ./tools/notices > THIRD_PARTY_NOTICES.md
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func kind(text string) string {
	switch {
	case strings.Contains(text, "Apache License") && strings.Contains(text, "Version 2.0"):
		return "Apache-2.0"
	case strings.Contains(text, "Permission is hereby granted, free of charge"):
		return "MIT"
	case strings.Contains(text, "Redistribution and use in source and binary forms"):
		if strings.Contains(text, "Neither the name") {
			return "BSD-3-Clause"
		}
		return "BSD-2-Clause"
	case strings.Contains(text, "CC0 1.0 Universal"):
		return "CC0-1.0"
	}
	return "see text"
}

func main() {
	out, err := exec.Command("go", "list", "-deps", "-f", "{{if .Module}}{{if not .Standard}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}{{end}}{{end}}", "./cmd/zweep-server").Output()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	mods := map[string][2]string{}
	sc := bufio.NewScanner(bytes.NewReader(out))
	for sc.Scan() {
		p := strings.Split(sc.Text(), "|")
		if len(p) == 3 && !strings.HasPrefix(p[0], "github.com/n1k0droid/zweep") {
			mods[p[0]] = [2]string{p[1], p[2]}
		}
	}
	if goroot, err := exec.Command("go", "env", "GOROOT").Output(); err == nil {
		v, _ := exec.Command("go", "env", "GOVERSION").Output()
		mods["Go standard library and runtime"] = [2]string{strings.TrimSpace(string(v)), strings.TrimSpace(string(goroot))}
	}
	names := make([]string, 0, len(mods))
	for n := range mods {
		names = append(names, n)
	}
	sort.Strings(names)
	fmt.Println("# Third-party notices")
	fmt.Println()
	fmt.Println("The Zweep server binary includes the following open source modules. Generated by `go run ./tools/notices`; do not edit.")
	fmt.Println()
	fmt.Println("| Module | Version | License |")
	fmt.Println("|---|---|---|")
	type entry struct{ name, version, license, text, notice string }
	var entries []entry
	for _, n := range names {
		dir := mods[n][1]
		var text, notice string
		files, _ := os.ReadDir(dir)
		for _, f := range files {
			up := strings.ToUpper(f.Name())
			b, err := os.ReadFile(filepath.Join(dir, f.Name())) // #nosec G304 -- module cache
			if err != nil {
				continue
			}
			switch {
			case strings.HasPrefix(up, "LICENSE") || strings.HasPrefix(up, "COPYING"):
				text += string(b)
			case strings.HasPrefix(up, "NOTICE"):
				notice += string(b)
			}
		}
		e := entry{n, mods[n][0], kind(text), text, notice}
		entries = append(entries, e)
		fmt.Printf("| %s | %s | %s |\n", e.name, e.version, e.license)
	}
	for _, e := range entries {
		fmt.Printf("\n## %s %s\n\n", e.name, e.version)
		if e.notice != "" {
			fmt.Printf("NOTICE:\n\n```\n%s\n```\n\n", strings.TrimSpace(e.notice))
		}
		fmt.Printf("```\n%s\n```\n", strings.TrimSpace(e.text))
	}
}
