// Copyright 2026 N1k0droid
// SPDX-License-Identifier: AGPL-3.0-only

// Package tlsmgr serves HTTPS (phase 8): self-signed, uploaded or ACME certificates (Let's Encrypt or an
// internal CA, renewed automatically), or none when a reverse proxy terminates TLS. Settings, keys and
// certificates live in the database, sealed with the master key, and are shared by every node.
package tlsmgr

import (
	"context"
	"crypto/ecdsa"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"net"
	"net/http"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/caddyserver/certmagic"
	"github.com/libdns/acmedns"
	"github.com/libdns/cloudflare"
	"github.com/libdns/ovh"
	"github.com/libdns/route53"
	"github.com/mholt/acmez/v3/acme"
)

// Modes
const (
	ModeOff        = "off"        // plain HTTP: a reverse proxy terminates TLS (or a lab)
	ModeSelfSigned = "selfsigned" // generated by Zweep; the app pins its key (enrollment QR code)
	ModeUpload     = "upload"     // bought or issued by the company CA (.cer/.crt/.pem + .key, .pfx)
	ModeACME       = "acme"       // Let's Encrypt or an internal ACME CA, renewed automatically
)

// ACME settings
const (
	CALetsEncrypt        = "letsencrypt"
	CALetsEncryptStaging = "letsencrypt-staging"
	CACustom             = "custom"

	ChallengeHTTP    = "http-01"     // port 80 reachable from the Internet
	ChallengeTLSALPN = "tls-alpn-01" // port 443 reachable from the Internet
	ChallengeDNS     = "dns-01"      // a DNS provider with an API: internal servers too
)

// DNSProviders are the DNS-01 providers and the credentials each one needs
var DNSProviders = map[string][]string{
	"cloudflare": {"api_token"},
	"route53":    {"access_key_id", "secret_access_key", "region", "hosted_zone_id"},
	"ovh":        {"endpoint", "application_key", "application_secret", "consumer_key"},
	"acmedns":    {"server_url", "username", "password", "subdomain"},
}

// secretFields are never shown back nor written to the audit trail
var secretFields = []string{"api_token", "secret_access_key", "application_secret", "consumer_key", "password"}

// ACME is the configuration of an ACME issuer
type ACME struct {
	CA           string            `json:"ca"`
	DirectoryURL string            `json:"directory_url,omitempty"` // custom CA
	RootPEM      string            `json:"root_pem,omitempty"`      // custom CA: its root, when not public
	EABKeyID     string            `json:"eab_key_id,omitempty"`    // External Account Binding (some CAs)
	EABMACKey    string            `json:"eab_mac_key,omitempty"`
	Email        string            `json:"email,omitempty"`
	Challenge    string            `json:"challenge"`
	DNSProvider  string            `json:"dns_provider,omitempty"`
	DNS          map[string]string `json:"dns,omitempty"`
}

// Settings of HTTPS, edited in the dashboard
type Settings struct {
	Mode  string   `json:"mode"`
	Names []string `json:"names,omitempty"` // self-signed: host names and addresses; ACME: domains
	ACME  ACME     `json:"acme"`
	// AllowPlain keeps plain HTTP besides HTTPS on the same ports (lab, migration); never with Internet
	AllowPlain bool `json:"allow_plain"`
	// Internet: the server is reachable from the Internet (explicit); HTTPS becomes mandatory
	Internet bool `json:"internet"`
	// Port 80 (listener ZWEEP_LISTEN_PLAIN): redirect to HTTPS for these addresses; the ACME HTTP-01
	// challenge path is always answered when that challenge is configured
	Port80Redirect bool     `json:"port80_redirect"`
	Port80Allowed  []string `json:"port80_allowed,omitempty"`
	// QRPin: the key fingerprint put in the enrollment QR code, for certificates the phones do not
	// trust by themselves: auto (self-signed: the certificate; internal ACME CA: the CA), none, leaf, ca
	QRPin     string    `json:"qr_pin,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy string    `json:"updated_by"`
}

// Redacted is the settings without secrets (audit, status)
func (s Settings) Redacted() Settings {
	out := s
	out.ACME.DNS = map[string]string{}
	for k, v := range s.ACME.DNS {
		if slices.Contains(secretFields, k) && v != "" {
			v = "********"
		}
		out.ACME.DNS[k] = v
	}
	if out.ACME.EABMACKey != "" {
		out.ACME.EABMACKey = "********"
	}
	return out
}

// Status is what the dashboard shows
type Status struct {
	Settings  Settings  `json:"settings"`
	Info      *Info     `json:"info,omitempty"`
	Fallback  bool      `json:"fallback"` // ACME certificate not obtained yet: the self-signed one is served
	LastError string    `json:"last_error,omitempty"`
	ErrorAt   time.Time `json:"error_at,omitempty"`
	Obtained  time.Time `json:"obtained,omitempty"` // last ACME issuance or renewal
}

// Events reports what happens (audit trail): name and details without secrets
type Events func(ctx context.Context, name string, details map[string]any)

// Manager serves the certificates
type Manager struct {
	st       *Storage
	defaults []string // names for the self-signed certificate: hosts of the service URLs
	events   Events

	mu       sync.RWMutex
	set      Settings
	modified time.Time
	static   *tls.Certificate // self-signed or uploaded
	selfCert *tls.Certificate // fallback while ACME obtains the certificate
	info     *Info
	magic    *certmagic.Config
	issuer   *certmagic.ACMEIssuer
	cache    *certmagic.Cache
	lastErr  string
	errAt    time.Time
	obtained time.Time
}

const settingsKey = "zweep/settings"

// New creates the manager; Start loads the settings
func New(st *Storage, defaults []string, events Events) *Manager {
	if events == nil {
		events = func(context.Context, string, map[string]any) {}
	}
	return &Manager{st: st, defaults: defaults, events: events, set: Settings{Mode: ModeOff}}
}

// Start loads the settings and follows their changes made on other nodes
func (m *Manager) Start(ctx context.Context) error {
	if err := m.reload(ctx, true); err != nil {
		return err
	}
	go func() {
		t := time.NewTicker(20 * time.Second)
		defer t.Stop()
		for {
			select {
			case <-ctx.Done():
				m.stopACME()
				return
			case <-t.C:
				if err := m.reload(ctx, false); err != nil && ctx.Err() == nil {
					slog.Warn("Cannot reload the HTTPS settings", "component", "tls", "err", err)
				}
			}
		}
	}()
	return nil
}

// reload reads the settings and rebuilds when they changed (or always when force)
func (m *Manager) reload(ctx context.Context, force bool) error {
	info, err := m.st.Stat(ctx, settingsKey)
	if errors.Is(err, fs.ErrNotExist) {
		return m.build(ctx, Settings{Mode: ModeOff})
	}
	if err != nil {
		return err
	}
	m.mu.RLock()
	same := !force && info.Modified.Equal(m.modified)
	m.mu.RUnlock()
	if same {
		return nil
	}
	raw, err := m.st.Load(ctx, settingsKey)
	if err != nil {
		return err
	}
	var s Settings
	if err := json.Unmarshal(raw, &s); err != nil {
		return err
	}
	if err := m.build(ctx, s); err != nil {
		slog.Error("HTTPS settings not applied", "component", "tls", "mode", s.Mode, "err", err)
		m.setError(err)
	}
	m.mu.Lock()
	m.modified = info.Modified
	m.mu.Unlock()
	return nil
}

// Validate checks settings before they are saved
func (m *Manager) Validate(s Settings) error {
	switch s.Mode {
	case ModeOff, ModeSelfSigned, ModeUpload:
	case ModeACME:
		if len(s.Names) == 0 {
			return errors.New("domains: at least one name")
		}
		for _, n := range s.Names {
			if net.ParseIP(n) != nil || !strings.Contains(n, ".") {
				return fmt.Errorf("domains: %q is not a public domain name", n)
			}
		}
		switch s.ACME.CA {
		case CALetsEncrypt, CALetsEncryptStaging:
		case CACustom:
			if !strings.HasPrefix(s.ACME.DirectoryURL, "https://") {
				return errors.New("directory_url: the ACME directory of the CA, https://")
			}
			if s.ACME.RootPEM != "" {
				if ok := x509.NewCertPool().AppendCertsFromPEM([]byte(s.ACME.RootPEM)); !ok {
					return errors.New("root_pem: not a PEM certificate")
				}
			}
		default:
			return errors.New("ca: unknown certificate authority")
		}
		switch s.ACME.Challenge {
		case ChallengeHTTP, ChallengeTLSALPN:
			if !s.Internet && s.ACME.CA != CACustom {
				// Let's Encrypt validates from the Internet: only a server published there can pass
				return errors.New("challenge: http-01 and tls-alpn-01 need the server reachable from the Internet; use dns-01, an internal ACME CA or a reverse proxy")
			}
		case ChallengeDNS:
			fields, ok := DNSProviders[s.ACME.DNSProvider]
			if !ok {
				return errors.New("dns_provider: unknown provider")
			}
			for _, f := range fields {
				if f == "hosted_zone_id" || f == "region" || (s.ACME.DNSProvider == "acmedns" && f == "subdomain") {
					continue // optional
				}
				if strings.TrimSpace(s.ACME.DNS[f]) == "" {
					return fmt.Errorf("dns.%s: required", f)
				}
			}
		default:
			return errors.New("challenge: http-01, tls-alpn-01 or dns-01")
		}
	default:
		return errors.New("mode: off, selfsigned, upload or acme")
	}
	if s.Internet && s.Mode == ModeOff {
		// Behind a reverse proxy the proxy is what the Internet reaches: allowed, HTTPS is its job
		return nil
	}
	for _, c := range s.Port80Allowed {
		if _, err := parsePrefix(c); err != nil {
			return fmt.Errorf("port80_allowed: %q is not an address or a CIDR", c)
		}
	}
	return nil
}

// Apply validates, stores and applies new settings; upload carries a new certificate for ModeUpload.
// Every node picks them up within seconds.
func (m *Manager) Apply(ctx context.Context, s Settings, upload *Parsed, by string) error {
	if s.Internet {
		s.AllowPlain = false
	}
	if err := m.Validate(s); err != nil {
		return err
	}
	if s.Mode == ModeUpload {
		if upload != nil {
			if err := m.st.Store(ctx, "zweep/upload/cert.pem", upload.CertPEM); err != nil {
				return err
			}
			if err := m.st.Store(ctx, "zweep/upload/key.pem", upload.KeyPEM); err != nil {
				return err
			}
		} else if !m.st.Exists(ctx, "zweep/upload/cert.pem") {
			return errors.New("certificate: upload the certificate and its key")
		}
	}
	s.UpdatedAt, s.UpdatedBy = time.Now().UTC(), by
	raw, err := json.Marshal(s)
	if err != nil {
		return err
	}
	if err := m.st.Store(ctx, settingsKey, raw); err != nil {
		return err
	}
	return m.reload(ctx, true)
}

// build prepares the certificates of the settings
func (m *Manager) build(ctx context.Context, s Settings) error {
	self, err := m.selfSigned(ctx, s)
	if err != nil {
		return err
	}
	var static *tls.Certificate
	var info *Info
	switch s.Mode {
	case ModeSelfSigned:
		static, info = self, infoOfTLS(self)
	case ModeUpload:
		certPEM, err := m.st.Load(ctx, "zweep/upload/cert.pem")
		if err != nil {
			return fmt.Errorf("uploaded certificate: %w", err)
		}
		keyPEM, err := m.st.Load(ctx, "zweep/upload/key.pem")
		if err != nil {
			return fmt.Errorf("uploaded key: %w", err)
		}
		c, err := tls.X509KeyPair(certPEM, keyPEM)
		if err != nil {
			return err
		}
		static, info = &c, infoOfTLS(&c)
	}
	m.stopACME()
	m.mu.Lock()
	m.set, m.static, m.info, m.selfCert = s, static, info, self
	m.lastErr = ""
	m.mu.Unlock()
	if s.Mode == ModeACME {
		return m.startACME(ctx, s)
	}
	slog.Info("HTTPS configured", "component", "tls", "mode", s.Mode)
	return nil
}

// selfSigned returns the self-signed certificate (also the fallback while ACME works), creating the key
// once and renewing the certificate with the same key when it is old or the names changed
func (m *Manager) selfSigned(ctx context.Context, s Settings) (*tls.Certificate, error) {
	names := s.Names
	if s.Mode != ModeSelfSigned || len(names) == 0 {
		names = m.defaults
	}
	keyPEM, err := m.st.Load(ctx, "zweep/selfsigned/key.pem")
	var key *ecdsa.PrivateKey
	switch {
	case errors.Is(err, fs.ErrNotExist):
		if key, err = NewKey(); err != nil {
			return nil, err
		}
		der, err := x509.MarshalECPrivateKey(key)
		if err != nil {
			return nil, err
		}
		keyPEM = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: der})
		if err := m.st.Store(ctx, "zweep/selfsigned/key.pem", keyPEM); err != nil {
			return nil, err
		}
	case err != nil:
		return nil, err
	default:
		b, _ := pem.Decode(keyPEM)
		if b == nil {
			return nil, errors.New("self-signed key unreadable")
		}
		if key, err = x509.ParseECPrivateKey(b.Bytes); err != nil {
			return nil, err
		}
	}
	certPEM, err := m.st.Load(ctx, "zweep/selfsigned/cert.pem")
	if err == nil {
		if c, err := tls.X509KeyPair(certPEM, keyPEM); err == nil {
			i := infoOfTLS(&c)
			if time.Until(i.NotAfter) > 30*24*time.Hour && sameNames(i.Names, names) {
				return &c, nil
			}
		}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}
	if certPEM, err = SelfSigned(key, names, time.Now()); err != nil {
		return nil, err
	}
	if err := m.st.Store(ctx, "zweep/selfsigned/cert.pem", certPEM); err != nil {
		return nil, err
	}
	c, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

func sameNames(a, b []string) bool {
	x, y := slices.Clone(a), slices.Clone(b)
	slices.Sort(x)
	slices.Sort(y)
	return slices.Equal(x, y)
}

func infoOfTLS(c *tls.Certificate) *Info {
	if c == nil || len(c.Certificate) == 0 {
		return nil
	}
	var chain []*x509.Certificate
	for _, der := range c.Certificate {
		if x, err := x509.ParseCertificate(der); err == nil {
			chain = append(chain, x)
		}
	}
	if len(chain) == 0 {
		return nil
	}
	i := InfoOf(chain)
	return &i
}

// ---- ACME ----

func (m *Manager) startACME(ctx context.Context, s Settings) error {
	var magic *certmagic.Config
	cache := certmagic.NewCache(certmagic.CacheOptions{
		GetConfigForCert: func(certmagic.Certificate) (*certmagic.Config, error) { return magic, nil },
		Logger:           zapLogger(),
	})
	magic = certmagic.New(cache, certmagic.Config{
		Storage: m.st,
		Logger:  zapLogger(),
		// Same key at every renewal: a fingerprint pinned by some client survives the renewals
		ReusePrivateKeys: true,
		OnEvent:          m.onEvent,
	})
	tpl := certmagic.ACMEIssuer{
		Email:  s.ACME.Email,
		Agreed: true,
		Logger: zapLogger(),
	}
	switch s.ACME.CA {
	case CALetsEncrypt:
		tpl.CA = certmagic.LetsEncryptProductionCA
	case CALetsEncryptStaging:
		tpl.CA = certmagic.LetsEncryptStagingCA
	case CACustom:
		tpl.CA = s.ACME.DirectoryURL
		if s.ACME.RootPEM != "" {
			pool := x509.NewCertPool()
			pool.AppendCertsFromPEM([]byte(s.ACME.RootPEM))
			tpl.TrustedRoots = pool
		}
	}
	if s.ACME.EABKeyID != "" {
		tpl.ExternalAccount = &acme.EAB{KeyID: s.ACME.EABKeyID, MACKey: s.ACME.EABMACKey}
	}
	switch s.ACME.Challenge {
	case ChallengeHTTP:
		tpl.DisableTLSALPNChallenge = true
	case ChallengeTLSALPN:
		tpl.DisableHTTPChallenge = true
	case ChallengeDNS:
		tpl.DisableHTTPChallenge, tpl.DisableTLSALPNChallenge = true, true
		p, err := dnsProvider(s.ACME)
		if err != nil {
			return err
		}
		tpl.DNS01Solver = &certmagic.DNS01Solver{DNSManager: certmagic.DNSManager{DNSProvider: p}}
	}
	issuer := certmagic.NewACMEIssuer(magic, tpl)
	magic.Issuers = []certmagic.Issuer{issuer}
	m.mu.Lock()
	m.magic, m.issuer, m.cache = magic, issuer, cache
	m.mu.Unlock()
	slog.Info("HTTPS with ACME", "component", "tls", "ca", s.ACME.CA, "challenge", s.ACME.Challenge, "domains", s.Names)
	// Obtains in the background, renews before a third of the validity is left (or when the CA says so, ARI)
	return magic.ManageAsync(context.WithoutCancel(ctx), s.Names)
}

func (m *Manager) stopACME() {
	m.mu.Lock()
	cache := m.cache
	m.magic, m.issuer, m.cache = nil, nil, nil
	m.mu.Unlock()
	if cache != nil {
		cache.Stop()
	}
}

func dnsProvider(a ACME) (certmagic.DNSProvider, error) {
	d := a.DNS
	switch a.DNSProvider {
	case "cloudflare":
		return &cloudflare.Provider{APIToken: d["api_token"]}, nil
	case "route53":
		return &route53.Provider{AccessKeyId: d["access_key_id"], SecretAccessKey: d["secret_access_key"], Region: d["region"], HostedZoneID: d["hosted_zone_id"]}, nil
	case "ovh":
		return &ovh.Provider{Endpoint: d["endpoint"], ApplicationKey: d["application_key"], ApplicationSecret: d["application_secret"], ConsumerKey: d["consumer_key"]}, nil
	case "acmedns":
		return &acmedns.Provider{ServerURL: d["server_url"], Username: d["username"], Password: d["password"], Subdomain: d["subdomain"]}, nil
	}
	return nil, errors.New("unknown DNS provider")
}

// onEvent records issuance and failures (audit trail, status)
func (m *Manager) onEvent(ctx context.Context, event string, data map[string]any) error {
	switch event {
	case "cert_obtained":
		m.mu.Lock()
		m.lastErr, m.obtained = "", time.Now()
		m.mu.Unlock()
		slog.Info("Certificate obtained", "component", "tls", "identifier", data["identifier"], "renewal", data["renewal"])
		m.events(ctx, "tls.cert_obtained", map[string]any{"identifier": data["identifier"], "renewal": data["renewal"], "issuer": data["issuer"]})
	case "cert_failed":
		err := fmt.Sprint(data["error"])
		m.setError(errors.New(err))
		slog.Error("Certificate not obtained", "component", "tls", "identifier", data["identifier"], "renewal", data["renewal"], "err", err)
		m.events(ctx, "tls.cert_failed", map[string]any{"identifier": data["identifier"], "renewal": data["renewal"], "error": err})
	}
	return nil
}

func (m *Manager) setError(err error) {
	m.mu.Lock()
	m.lastErr, m.errAt = err.Error(), time.Now()
	m.mu.Unlock()
}

// ---- serving ----

// Enabled reports whether HTTPS is served
func (m *Manager) Enabled() bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.set.Mode != ModeOff
}

// PlainAllowed reports whether plain HTTP requests are served (not redirected)
func (m *Manager) PlainAllowed() bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.set.Mode == ModeOff || (m.set.AllowPlain && !m.set.Internet)
}

// Settings returns the current settings (with secrets: for the editor only)
func (m *Manager) Settings() Settings {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.set
}

// Status describes the certificate in use
func (m *Manager) Status() Status {
	m.mu.RLock()
	defer m.mu.RUnlock()
	st := Status{Settings: m.set.Redacted(), Info: m.info, LastError: m.lastErr, ErrorAt: m.errAt, Obtained: m.obtained}
	if m.set.Mode == ModeACME && m.magic != nil {
		if c, err := m.magic.CacheManagedCertificate(context.Background(), firstOr(m.set.Names)); err == nil {
			i := InfoOf(leafChain(c.Certificate))
			st.Info = &i
		} else {
			st.Fallback = true
			st.Info = infoOfTLS(m.selfCert)
		}
	}
	return st
}

func firstOr(v []string) string {
	if len(v) == 0 {
		return ""
	}
	return v[0]
}

func leafChain(c tls.Certificate) []*x509.Certificate {
	var out []*x509.Certificate
	for _, der := range c.Certificate {
		if x, err := x509.ParseCertificate(der); err == nil {
			out = append(out, x)
		}
	}
	if len(out) == 0 {
		out = []*x509.Certificate{{}}
	}
	return out
}

// TLSConfig is the configuration of the HTTPS listeners: the certificate is chosen at every handshake,
// so a change of settings or a renewal takes effect without restart
func (m *Manager) TLSConfig() *tls.Config {
	return &tls.Config{
		MinVersion: tls.VersionTLS12,
		NextProtos: []string{"http/1.1", "acme-tls/1"}, // HTTP/1.1: the app stream is a WebSocket
		GetCertificate: func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
			m.mu.RLock()
			magic, static, self := m.magic, m.static, m.selfCert
			m.mu.RUnlock()
			if magic != nil {
				c, err := magic.GetCertificate(hello)
				if err == nil {
					return c, nil
				}
				// Until the CA issues it (or when it fails), the self-signed certificate keeps the
				// dashboard reachable: the status page tells what is wrong
				return self, nil
			}
			if static != nil {
				return static, nil
			}
			if self != nil {
				return self, nil
			}
			return nil, errors.New("no certificate")
		},
	}
}

// HTTPChallenge answers an ACME HTTP-01 challenge; false when the request is something else
func (m *Manager) HTTPChallenge(w http.ResponseWriter, r *http.Request) bool {
	m.mu.RLock()
	issuer := m.issuer
	m.mu.RUnlock()
	return issuer != nil && issuer.HandleHTTPChallenge(w, r)
}

// Port80 returns what the plain port does: redirect allowed for an address
func (m *Manager) Port80(ip net.IP) (redirect bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if !m.set.Port80Redirect {
		return false
	}
	if len(m.set.Port80Allowed) == 0 {
		return true
	}
	for _, c := range m.set.Port80Allowed {
		if p, err := parsePrefix(c); err == nil && ip != nil && p.Contains(ip) {
			return true
		}
	}
	return false
}

func parsePrefix(s string) (*net.IPNet, error) {
	s = strings.TrimSpace(s)
	if !strings.Contains(s, "/") {
		ip := net.ParseIP(s)
		if ip == nil {
			return nil, errors.New("invalid address")
		}
		bits := 32
		if ip.To4() == nil {
			bits = 128
		}
		return &net.IPNet{IP: ip, Mask: net.CIDRMask(bits, bits)}, nil
	}
	_, n, err := net.ParseCIDR(s)
	return n, err
}

// Pin is the fingerprint for the enrollment QR code, empty when the phones trust the certificate
// by themselves (public CA, or a company CA installed on the phones)
func (m *Manager) Pin() string {
	m.mu.RLock()
	mode, choice, ca := m.set.Mode, m.set.QRPin, m.set.ACME.CA
	m.mu.RUnlock()
	if mode == ModeOff {
		return ""
	}
	if choice == "" || choice == "auto" {
		switch {
		case mode == ModeSelfSigned:
			choice = "leaf"
		case mode == ModeACME && ca == CACustom:
			choice = "ca"
		default:
			choice = "none"
		}
	}
	if choice == "none" {
		return ""
	}
	cert, err := m.TLSConfig().GetCertificate(&tls.ClientHelloInfo{ServerName: m.firstName()})
	if err != nil || cert == nil || len(cert.Certificate) == 0 {
		return ""
	}
	der := cert.Certificate[0]
	if choice == "ca" && len(cert.Certificate) > 1 {
		// The top of the chain sent: stays the same across renewals by the same CA
		der = cert.Certificate[len(cert.Certificate)-1]
	}
	x, err := x509.ParseCertificate(der)
	if err != nil {
		return ""
	}
	return SPKIPin(x)
}

func (m *Manager) firstName() string {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return firstOr(m.set.Names)
}

// URL turns an http:// service URL into https:// as soon as HTTPS is served (QR code, app
// configuration, media type): same host and port, the listeners serve both. Plain HTTP kept on
// request only lets the old clients work while they move.
func (m *Manager) URL(u string) string {
	if m == nil || !m.Enabled() || !strings.HasPrefix(u, "http://") {
		return u
	}
	return "https://" + strings.TrimPrefix(u, "http://")
}

// RedirectHost keeps a redirect on this server: the Host of the request when it is one of the names
// of the server (service URLs, certificate names), otherwise the first of them. A forged Host header
// never sends a client elsewhere.
func (m *Manager) RedirectHost(hostport string) string {
	host, port, err := net.SplitHostPort(hostport)
	if err != nil {
		host, port = hostport, ""
	}
	m.mu.RLock()
	known := append(slices.Clone(m.defaults), m.set.Names...)
	m.mu.RUnlock()
	if !slices.ContainsFunc(known, func(n string) bool { return strings.EqualFold(n, host) }) {
		if len(known) == 0 {
			return "localhost"
		}
		host = known[0]
	}
	if port != "" {
		return net.JoinHostPort(host, port)
	}
	return host
}
